#!/bin/sh

bspc config border_width			4
bspc config window_gap				16
bspc config top_padding				24

bspc config split_ratio				0.52
bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config focus_by_distance		true

bspc config focus_follows_pointer	true

bspc monitor eDP1 -d · ·· ··· ···· ·····
